-- Plant 1

CREATE TABLE plant1_power_data (
    DATE_TIME DATETIME,
    PLANT_ID INT,
    SOURCE_KEY NVARCHAR(255), -- Adjust the length as needed
    DC_POWER FLOAT,
    AC_POWER FLOAT,
    DAILY_YIELD FLOAT,
    TOTAL_YIELD FLOAT,
    INVERTER_EFFICIENCY FLOAT,
    DAILY_POWER_PRODUCTION_AC FLOAT,
    DAILY_POWER_PRODUCTION_DC FLOAT,
    AC_PERFORMANCE_RATIO FLOAT,
    DC_PERFORMANCE_RATIO FLOAT,
    DAILY_INCREMENTAL_YIELD FLOAT,
    AMBIENT_TEMPERATURE FLOAT,
    MODULE_TEMPERATURE FLOAT,
    IRRADIATION FLOAT,
    TEMP_DIFFERENCE FLOAT,
    DAILY_IRRADIATION_TOTAL FLOAT
);

-- Plant 2

CREATE TABLE plant2_power_data (
    DATE_TIME DATETIME,
    PLANT_ID INT,
    SOURCE_KEY NVARCHAR(255), -- Adjust the length as needed
    DC_POWER FLOAT,
    AC_POWER FLOAT,
    DAILY_YIELD FLOAT,
    TOTAL_YIELD FLOAT,
    INVERTER_EFFICIENCY FLOAT,
    DAILY_POWER_PRODUCTION_AC FLOAT,
    DAILY_POWER_PRODUCTION_DC FLOAT,
    AC_PERFORMANCE_RATIO FLOAT,
    DC_PERFORMANCE_RATIO FLOAT,
    DAILY_INCREMENTAL_YIELD FLOAT,
    AMBIENT_TEMPERATURE FLOAT,
    MODULE_TEMPERATURE FLOAT,
    IRRADIATION FLOAT,
    TEMP_DIFFERENCE FLOAT,
    DAILY_IRRADIATION_TOTAL FLOAT
);
